char key_name[] = "testkey";
char client_type[] = "";
char client_arch[] = "";
char client_creator[] = "";
char client_comments[] = "";
char client_key_date[] = "August 2026";

/*
 * DO NOT EDIT THIS FILE!!! GENERATED AUTOMATICALLY!!!
 *
 * mkkey version [RES-RSA 2.9.2: Mar. 13, 2000][GMP]
 */

#include <stdio.h>
#include <gmp.h>

/* rsa_partial_box prototypes */
void rsa_partial_box_0(MP_INT *, MP_INT *, MP_INT *);
void rsa_partial_box_1(MP_INT *, MP_INT *, MP_INT *);
void rsa_partial_box_2(MP_INT *, MP_INT *, MP_INT *);
void rsa_partial_box_3(MP_INT *, MP_INT *, MP_INT *);
void rsa_partial_box_4(MP_INT *, MP_INT *, MP_INT *);


void rsa_black_box(unsigned char *out, unsigned char *in,
                   unsigned char *public, unsigned char *global) {

  MP_INT m_msg;
  MP_INT m_result;
  MP_INT m_public;
  MP_INT m_global;
  MP_INT m_tmp;
  int i;
  mpz_init(&m_msg);
  mpz_init(&m_result);
  mpz_init(&m_public);
  mpz_init(&m_global);
  mpz_init(&m_tmp);
  for (i = 0; i < 32; i++) {
    mpz_mul_2exp(&m_msg, &m_msg, 8);
    mpz_add_ui(&m_msg, &m_msg, in[32-1-i]);
  }
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x769e2851);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x563c03b1);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0xd7df7fe8);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x392d040f);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x8358ef7);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x1122a8ec);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0x9ed637d9);
  mpz_mul_2exp(&m_global, &m_global, 32);
  mpz_add_ui(&m_global, &m_global, (unsigned long) 0xec111ccb);
  if (global != NULL) {
    global[0] = 203;
    global[1] = 28;
    global[2] = 17;
    global[3] = 236;
    global[4] = 217;
    global[5] = 55;
    global[6] = 214;
    global[7] = 158;
    global[8] = 236;
    global[9] = 168;
    global[10] = 34;
    global[11] = 17;
    global[12] = 247;
    global[13] = 142;
    global[14] = 53;
    global[15] = 8;
    global[16] = 15;
    global[17] = 4;
    global[18] = 45;
    global[19] = 57;
    global[20] = 232;
    global[21] = 127;
    global[22] = 223;
    global[23] = 215;
    global[24] = 177;
    global[25] = 3;
    global[26] = 60;
    global[27] = 86;
    global[28] = 81;
    global[29] = 40;
    global[30] = 158;
    global[31] = 118;
  }
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0x735f7e1c);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0x86e136f2);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0x69da2341);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0x9d2d007e);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0xa5844ce5);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0xac6b7c4d);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0x51ee3b7c);
  mpz_mul_2exp(&m_public, &m_public, 32);
  mpz_add_ui(&m_public, &m_public, (unsigned long) 0xc70d9e4f);
  if (public != NULL) {
    public[0] = 79;
    public[1] = 158;
    public[2] = 13;
    public[3] = 199;
    public[4] = 124;
    public[5] = 59;
    public[6] = 238;
    public[7] = 81;
    public[8] = 77;
    public[9] = 124;
    public[10] = 107;
    public[11] = 172;
    public[12] = 229;
    public[13] = 76;
    public[14] = 132;
    public[15] = 165;
    public[16] = 126;
    public[17] = 0;
    public[18] = 45;
    public[19] = 157;
    public[20] = 65;
    public[21] = 35;
    public[22] = 218;
    public[23] = 105;
    public[24] = 242;
    public[25] = 54;
    public[26] = 225;
    public[27] = 134;
    public[28] = 28;
    public[29] = 126;
    public[30] = 95;
    public[31] = 115;
  }
  {
    MP_INT r[3], m[3];
    for (i = 0; i < 3; i++) {
      mpz_init_set_ui(&r[i], 1); mpz_init(&m[i]);
    }
    mpz_set(&m[1], &m_msg);
#define g &m_global
#define X(m, r, g) \
    mpz_mul(r, m, r);\
    mpz_mod(r, r, g)

#define Y(m, r, g) \
    mpz_mul(m, m, m);\
    mpz_mod(m, m, g)

#define SWAP(i, j) \
    { \
      MP_INT tmp; \
      tmp = m[i]; m[i] = m[j]; m[j] = tmp; \
      tmp = r[i]; r[i] = r[j]; r[j] = tmp; \
    }

    rsa_partial_box_0(m, r, &m_global);
    /* real_j is 0, bit 24 is 1 */
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 1);
    /* real_j is 0, bit 25 is 0 */
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 0, bit 26 is 0 */
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 0, bit 27 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 2);
    /* real_j is 0, bit 28 is 0 */
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 0, bit 29 is 0 */
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 0);
    SWAP(2, 2);
    /* real_j is 1, bit 30 is 0 */
    X(&m[0], &r[0], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    rsa_partial_box_1(m, r, &m_global);
    /* real_j is 0, bit 46 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 2);
    /* real_j is 0, bit 47 is 0 */
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 1);
    /* real_j is 0, bit 48 is 0 */
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 0, bit 49 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 0);
    SWAP(2, 1);
    /* real_j is 2, bit 50 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 2);
    /* real_j is 2, bit 51 is 1 */
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    rsa_partial_box_2(m, r, &m_global);
    /* real_j is 1, bit 74 is 0 */
    Y(&m[0], &r[0], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 75 is 1 */
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 2);
    /* real_j is 1, bit 76 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 1, bit 77 is 0 */
    Y(&m[0], &r[0], g);
    Y(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 1, bit 78 is 0 */
    X(&m[0], &r[0], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 79 is 0 */
    X(&m[0], &r[0], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 0);
    SWAP(2, 2);
    rsa_partial_box_3(m, r, &m_global);
    /* real_j is 1, bit 101 is 0 */
    X(&m[0], &r[0], g);
    Y(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 102 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 103 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 1, bit 104 is 1 */
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 105 is 1 */
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 106 is 0 */
    X(&m[0], &r[0], g);
    Y(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    /* real_j is 1, bit 107 is 0 */
    Y(&m[0], &r[0], g);
    Y(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    rsa_partial_box_4(m, r, &m_global);
    /* real_j is 0, bit 123 is 0 */
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 0, bit 124 is 1 */
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 0);
    /* real_j is 2, bit 125 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 2, bit 126 is 0 */
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 2, bit 127 is 1 */
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 1);
    /* real_j is 1, bit 128 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 1, bit 129 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 1);
    SWAP(2, 1);
    /* real_j is 2, bit 130 is 0 */
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 2, bit 131 is 1 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 2, bit 132 is 0 */
    X(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    /* real_j is 2, bit 133 is 1 */
    X(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);
    SWAP(0, 0);
    SWAP(1, 0);
    SWAP(2, 2);
    /* real_j is 2, bit 134 is 1 */
    Y(&m[0], &r[0], g);
    Y(&m[1], &r[1], g);
    X(&m[2], &r[2], g);
    Y(&m[0], &r[0], g);
    X(&m[1], &r[1], g);
    Y(&m[2], &r[2], g);

    mpz_set(&m_result, &r[2]);
    for (i = 0; i < 3; i++) {
      mpz_clear(&r[i]); mpz_clear(&m[i]);
    }
  }
  for (i = 0; i < 32; i++) {
    mpz_divmod_ui(&m_result, &m_tmp, &m_result, 256);
    *out++ = (unsigned char) mpz_get_ui(&m_tmp);
  }
  mpz_clear(&m_msg);
  mpz_clear(&m_result);
  mpz_clear(&m_public);
  mpz_clear(&m_global);
  mpz_clear(&m_tmp);
}
